### ISSUE TITLE
Relax test for allowed languages

### ISSUE THREAD

**Issue by stweil** [janis91/ocr#138]
The app is currently very restrictive regarding the allowed names for installed languages in the settings page. Thus administrators cannot install their own ~~`German.tessdata`~~ `German.traineddata` or use Tesseract 4 with the provided ~~`Latin.tessdata`~~ `Latin.traineddata`.

It should relax the test and allow any "reasonable" name.

**Comment by janis91** [comment]
Do you mean that a administrator should be able to add language names different then "deu, fra, deu-frak" into the settings input field for example?

**Comment by janis91** [comment]
Is "tessdata" the same as "traineddata" ?

**Comment by stweil** [comment]
Yes and yes. The settings field should allow entries like "Fraktur", "German", "Latin" or even "Canadian_Aboriginal", too (see list at https://github.com/tesseract-ocr/tessdata_fast).

And of course I should have written `German.traineddata`. That was a confusion on my side, caused by the directory name which includes those traineddata files.

**Comment by janis91** [comment]
Ok. That sounds very reasonable to me. I will relax the regex check.

**Comment by stweil** [comment]
Danke!

**Comment by janis91** [comment]
fixed in #139

**Comment by stweil** [comment]
It's still not possible to enter `Latin` without getting an error message. In addition, I changed [tessdata_fast](https://github.com/tesseract-ocr/tessdata_fast) today. Now for script data it looks like `script/Latin`, so slashes are also possible.

**Comment by janis91** [comment]
Now it should be fixed.. forgot the server side part :-D

**Comment by stweil** [comment]
I'm sorry that I don't have good news: the new language and script names still don't work in my installation.
